<?php

use Illuminate\Database\Seeder;

class EstabelecimentosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('estabelecimentos')->insert([
          'nome'=>'Flor da manhã',
          'email'=>'flor@gmail.com',
          'cnpj'=>'1234567891013',
          'endereco'=>'teste endereço',
          'cep'=>'1234567',
          'cidade'=>'Mogi das Cruzes',
          'estado'=>'São Paulo',
          'tel1'=>'5511123123123',
          'tel2'=>'55243243243',
          'celular'=>'551199999999',
          'descricao'=>'teste descricao',
          'wifi'=>'1',
          'cafeDaManha'=>null,
          'piscina'=>null,
          'sauna'=>'1',
          'permitePets'=>null,
          'cancelamentoGratuito'=>null,
          'numEstrelas'=>'1',
      ]);
      DB::table('estabelecimentos')->insert([
        'nome'=>'Paradise Plus',
        'email'=>'paradise@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'teste endereço',
        'cep'=>'1234567',
        'cidade'=>'Santos',
        'estado'=>'São Paulo',
        'tel1'=>'5511123123123',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'teste descricao',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>null,
        'cancelamentoGratuito'=>null,
        'numEstrelas'=>'1',
      ]);

      DB::table('estabelecimentos')->insert([
        'nome'=>'Joaquina Beach',
        'email'=>'joaquina@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Morro da Lagoa, 34',
        'cep'=>'1234567',
        'cidade'=>'Florianopolis',
        'estado'=>'Santa Cataria',
        'tel1'=>'5511123123123',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'teste descricao',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>null,
        'cancelamentoGratuito'=>null,
        'numEstrelas'=>'1',
      ]);

      DB::table('estabelecimentos')->insert([
        'nome'=>'Golden Palace Hotel',
        'email'=>'gold@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Estrada do ouro, 34',
        'cep'=>'1234567',
        'cidade'=>'Ouro Preto',
        'estado'=>'Minas Gerais',
        'tel1'=>'5511123123123',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'teste descricao',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>null,
        'cancelamentoGratuito'=>null,
        'numEstrelas'=>'1',
      ]);

      DB::table('estabelecimentos')->insert([
        'nome'=>'Copacabana Palace',
        'email'=>'copa@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Av Copacabana, 34',
        'cep'=>'1234567',
        'cidade'=>'Rio de Janeiro',
        'estado'=>'Rio de Janeiro',
        'tel1'=>'5511123123123',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'teste descricao',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>null,
        'cancelamentoGratuito'=>null,
        'numEstrelas'=>'1',
      ]);

      DB::table('estabelecimentos')->insert([
        'nome'=>'Pousada Boto Rosa',
        'email'=>'botorosa@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Ilha de Noronha, 34',
        'cep'=>'1234567',
        'cidade'=>'Fernando de noronha',
        'estado'=>'Pernanbuco',
        'tel1'=>'5511123123123',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'teste descricao',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>'0',
        'cancelamentoGratuito'=>'0',
        'numEstrelas'=>'1',
      ]);
      DB::table('estabelecimentos')->insert([
        'nome'=>'Rota do Sol Hotel',
        'email'=>'rotadosol@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Serra do Lopo, 34',
        'cep'=>'1234567',
        'cidade'=>'Extrema',
        'estado'=>'Minas Gerais',
        'tel1'=>'5511123123123',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'teste descricao',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>'0',
        'cancelamentoGratuito'=>'0',
        'numEstrelas'=>'1',
      ]);
      DB::table('estabelecimentos')->insert([
        'nome'=>'Leme praia Hotel',
        'email'=>'lemehotel@gmail.com',
        'cnpj'=>'1234567891013',
        'endereco'=>'Serra do Lopo, 34',
        'cep'=>'1234567',
        'cidade'=>'Rio de Janeiro',
        'estado'=>'Rio de Janeiro',
        'tel1'=>'5511123123123',
        'tel2'=>'55243243243',
        'celular'=>'551199999999',
        'descricao'=>'teste descricao',
        'wifi'=>'1',
        'cafeDaManha'=>'1',
        'piscina'=>'1',
        'sauna'=>'1',
        'permitePets'=>'0',
        'cancelamentoGratuito'=>'0',
        'numEstrelas'=>'1',
      ]);
      DB::table('estabelecimentos')->insert([
          'nome'=>'Recanto Feliz',
          'email'=>'feliz@gmail.com',
          'cnpj'=>'1234567891013',
          'endereco'=>'Rod Fernão Dia, km7',
          'cep'=>'1234567',
          'cidade'=>'Vargem',
          'estado'=>'São Paulo',
          'tel1'=>'5511123123123',
          'tel2'=>'55243243243',
          'celular'=>'551199999999',
          'descricao'=>'teste descricao',
          'wifi'=>'1',
          'cafeDaManha'=>'1',
          'piscina'=>'1',
          'sauna'=>'1',
          'permitePets'=>'0',
          'cancelamentoGratuito'=>'0',
          'numEstrelas'=>'1',
      ]);
      DB::table('estabelecimentos')->insert([
          'nome'=>'Pousada do Rio Quente',
          'email'=>'rioquante@gmail.com',
          'cnpj'=>'1234567891013',
          'endereco'=>'Rua Canto das maritacas, 8',
          'cep'=>'1234567',
          'cidade'=>'Porto de Galinhas',
          'estado'=>'Pernanbuco',
          'tel1'=>'5511123123123',
          'tel2'=>'55243243243',
          'celular'=>'551199999999',
          'descricao'=>'teste descricao',
          'wifi'=>'1',
          'cafeDaManha'=>'1',
          'piscina'=>'1',
          'sauna'=>'1',
          'permitePets'=>'0',
          'cancelamentoGratuito'=>'0',
          'numEstrelas'=>'1',
      ]);
      DB::table('estabelecimentos')->insert([
          'nome'=>'Dali Hotel',
          'email'=>'dali@gmail.com',
          'cnpj'=>'1234567891013',
          'endereco'=>'Rua dos artistas, 8',
          'cep'=>'1234567',
          'cidade'=>'Salvador',
          'estado'=>'Bahia',
          'tel1'=>'5511123123123',
          'tel2'=>'55243243243',
          'celular'=>'551199999999',
          'descricao'=>'teste descricao',
          'wifi'=>'1',
          'cafeDaManha'=>'1',
          'piscina'=>'1',
          'sauna'=>'1',
          'permitePets'=>'0',
          'cancelamentoGratuito'=>'0',
          'numEstrelas'=>'1',
      ]);
            DB::table('estabelecimentos')->insert([
              'nome'=>'Paraty33',
              'email'=>'paraty@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Rua das Gamelias, 8',
              'cep'=>'1234567',
              'cidade'=>'Paraty',
              'estado'=>'Rio de Janeiro',
              'tel1'=>'5511123123123',
              'tel2'=>'55243243243',
              'celular'=>'551199999999',
              'descricao'=>'teste descricao',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'0',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'1',
                  ]);

            DB::table('estabelecimentos')->insert([
              'nome'=>'Long Beach hotel',
              'email'=>'longBeach@gmail.com',
              'cnpj'=>'1234567891013',
              'endereco'=>'Rua das Gamelias, 8',
              'cep'=>'1234567',
              'cidade'=>'Praia Grande',
              'estado'=>'São Paulo',
              'tel1'=>'5511123123123',
              'tel2'=>'55243243243',
              'celular'=>'551199999999',
              'descricao'=>'teste descricao',
              'wifi'=>'1',
              'cafeDaManha'=>'1',
              'piscina'=>'1',
              'sauna'=>'1',
              'permitePets'=>'0',
              'cancelamentoGratuito'=>'0',
              'numEstrelas'=>'1',
            ]);
    }
}
