<?php
$servicos =[
    ["id"=>1,"servico"=>1,"nome"=>"Esmeralda Praia",
     "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
     "info"=>"Esta acomodação fica a 2 minutos a pé da praia. Oferecendo um parque aquático com iluminação especial e acesso direto á Praia de Ponta Negra, o Esmeralda Praia Hotel apresenta vista panorâmica do Morro do Careca. Você pode desfrutar do regime de meia-pensão com café da manhã gratuito, jantar temático com música ao vivo e chá da tarde. O Esmeralda Praia Hotel dispõe de quartos espaçosos com uma varanda grande, ar-condicionado, TV a cabo e frigobar. Algumas acomodações contam com vista do mar. O WiFi gratuito está disponível em todas as áreas. O restaurante no local também serve um buffet de almoço bem como pratos nacionais e internacionais à la carte. A piscina possui jatos de hidromassagem e sistemas de iluminação para cromoterapia. Os adultos podem relaxar com os serviços do spa, enquanto as crianças podem se divertir no miniclube. O Esmeralda Praia fica próximo a lojas, restaurantes e bares. O Shopping Center Artesanato está a 400 metros, e o Shopping Sea Way fica a 2,2 km do local. O Aeroporto Internacional de São Gonçalo do Amarante está a 33 km do hotel. Praia de Ponta Negra é uma ótima escolha para viajantes interessados em caminhadas na praia, praias e paisagens.",
     "foto"=>"esmeralda-praia-hotel.jpg"],
    ["id"=>2,"servico"=>2,"nome"=>"Algarve",
     "avaliacao"=>3.9,"local"=>"Portugal","preco"=>1200,"desconto"=>35,
     "info"=>"Entre praias cinematográficas, grutas incríveis, formações rochosas imponentes e patrimônios históricos, confira o que fazer no Algarve com nossas dicas e roteiro de viagem de 7 dias por essa região de Portugal. Quem organiza um roteiro de viagem pela Europa espera encontrar belas cidades históricas e muito patrimônio cultural. Mas a verdade é que é possível também encontrar algumas das praias mais bonitas do mundo. A região do Algarve, em Portugal, é a confirmação disso. Caso você ainda tenha dúvida se vale a pena ou não incluir essa região no seu roteiro em Portugal, saiba que além de belíssima, a região do Algarve também é uma das opções mais econômicas de viagem na Europa.",
     "foto"=>"algarvePortugal.jpg"],
    ["id"=>3,"servico"=>2,"nome"=>"Lagos de Plitvice",
     "avaliacao"=>4.8,"local"=>"Croácia","preco"=>700,"desconto"=>0,
     "info"=>"Se você procura por paisagens naturais de tirar o fôlego e que parecem ser de mentira, os Lagos Plitvice na Croácia não irão decepcionar pois são um verdadeiro fenômeno da natureza, com paisagens únicas e de extrema beleza localizados na Croácia Central. O Parque Nacional dos Lagos Plitvice é a atração mais popular da Croácia e foi a primeira grande razão que me fez montar um roteiro pelo país. Uma simples foto dessa beleza natural me convenceu totalmente de que deveria fazer esta viagem e acho que assim como eu várias pessoas não se arrependeram da escolha! São 16 lagos conectados por uma série de cachoeiras. As cores das águas são de cair o queijo, numa variação entre diversos tons de azul e verde. O Parque dos Lagos Plitvice é gigante! Formado por uma rica fauna e flora local, já foram catalogadas mais de 1267 espécies de plantas, 55 tipos diferentes de orquídeas, 161 espécies de pássaros e 321 espécies de borboletas.",
     "foto"=>"LagosDePlitviceCroacia.jpg"],
    ["id"=>4,"servico"=>2,"nome"=>"Valletta",
     "avaliacao"=>4.1,"local"=>"Malta","preco"=>1500,"desconto"=>35,
     "info"=>"Um local quase obrigatório em Malta é sua capital, Valletta. Apesar de pequena, Valletta abriga uma grande concentração de prédios históricos: são 320 monumentos em apenas 0,5 km². Esse fator fez com que a cidade fosse declarada Patrimônio Mundial da Humanidade pela UNESCO.",
     "foto"=>"ValetaMalta.jpg"],
    ["id"=>5,"servico"=>2,"nome"=>"Banff",
      "avaliacao"=>3.6,"local"=>"Alberta","preco"=>1000,"desconto"=>15,
      "info"=>"s Montanhas Rochosas canadenses são mais do que o nome sugere. A região tem lindas montanhas que ficam cobertas por neve, geleiras e até cachoeiras em momentos de degelo; mas não há porque subestimá-las, há muito mais do que montanhas e essa é uma região de beleza infindável! Não é à toa que esse é um dos destinos mais bonitos do Canadá! Há bastantes coisas para ver e fazer em Banff e seus arredores e muitos dos atrativos são para contemplação, para apreciar a paisagem. É preciso notar que as atrações não se concentram unicamente em Banff ou no Parque Nacional de Banff e que você deverá sair da cidade para visitá-las, portanto, pode ser interessante reservar um tempo para fazer passeios para localidades mais afastadas e para visitar as atrações da própria cidade.",
      "foto"=>"Banff-AlbertaCanada.jpg"],
    ["id"=>6,"servico"=>2,"nome"=>"Amalfi",
      "avaliacao"=>4.5,"local"=>"Italia","preco"=>800,"desconto"=>0,
      "info"=>"A Costa Amalfitana é uma daquelas pérolas preciosas da Itália, que o mundo inteiro inveja. Uma parada imperdível quando você está na Costa Amalfitana, é Amalfi, que dá nome a toda a costa e está situada na foz do Valle dei Mulini, localizada sobre o mar e maravilhosamente colorido. Amalfi é um lugar de férias ideal, para muitos turistas e muitos curiosos dada a presença constante, durante todo o ano, de muitas celebridades, um lugar comparado com a Riviera Francesa e dos mais solicitados e populares. Foi a primeira das quatro Repúblicas Marítimas, e é nesse período que chega ao auge de seu esplendor. É um aglomerado de casas brancas agarradas à rocha e ligadas por becos e escadarias, e é considerada uma das pérolas da Costa Amalfitana.",
      "foto"=>"Amalfi-Italia.jpg"],
    ["id"=>7,"servico"=>2,"nome"=>"Castelo de Colomares",
      "avaliacao"=>2.8,"local"=>"Espanha","preco"=>1270,"desconto"=>35,
      "info"=>"O Castelo de Colomares, na Espanha é um monumento construído em homenagem a Cristovão Colombo, o explorador da época das Grandes Navegações.",
      "foto"=>"CastiloDeColomares-Espanha.jpg"],
    ["id"=>8,"servico"=>2,"nome"=>"Praga",
      "avaliacao"=>3.5,"local"=>"Republica Tcheca","preco"=>990,"desconto"=>15,
      "info"=>"Com uma arquitetura belíssima, repleta de vida cultural, museus e o maior castelo do mundo, Praga é um destino obrigatório a quem vai até o Leste Europeu. Em conjunto com Budapeste, Viena e Bratislava, forma um roteiro perfeitinho pela região. A capital da República Tcheca sofreu pouco durante as grandes guerras em relação às outras grandes cidades da Europa. Além disso, ficou por várias décadas isolada na Cortina de Ferro, por isso conserva muito de suas construções intactas. Mas se engana quem acha que a cidade tem somente atrações antigas por conta de suas construções medievais. Há também muitos pontos turísticos modernos como o Monumento e Museu em homenagem a Franz Kafka, e também a intrigante Casa Dançante.",
      "foto"=>"PragaRepublicaTcheca.jpg"],
  ];
?>
