<?php
$hoteis =[
    ["id"=>1,"servico"=>"Hospedagem","nome"=>"Esmeralda Praia",
     "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
     "info"=>"","foto"=>"esmeralda-praia-hotel.jpg"],
    ["id"=>2,"servico"=>"Hospedagem","nome"=>"Esmeralda Praia",
     "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
     "info"=>"","foto"=>"esmeralda-praia-hotel.jpg"],
    ["id"=>3,"servico"=>"Hospedagem","nome"=>"Esmeralda Praia",
     "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
     "info"=>"","foto"=>"esmeralda-praia-hotel.jpg"],
    ["id"=>4,"servico"=>"Hospedagem","nome"=>"Esmeralda Praia",
     "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
     "info"=>"","foto"=>"esmeralda-praia-hotel.jpg"],
    ["id"=>5,"servico"=>"Hospedagem","nome"=>"Esmeralda Praia",
      "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
      "info"=>"","foto"=>"esmeralda-praia-hotel.jpg"],
    ["id"=>6,"servico"=>"Hospedagem","nome"=>"Esmeralda Praia",
      "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
      "info"=>"","foto"=>"esmeralda-praia-hotel.jpg"],
    ["id"=>7,"servico"=>"Hospedagem","nome"=>"Esmeralda Praia",
      "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
      "info"=>"","foto"=>"esmeralda-praia-hotel.jpg"],
    ["id"=>8,"servico"=>"Hospedagem","nome"=>"Esmeralda Praia",
      "avaliacao"=>4.5,"local"=>"Brasil","preco"=>900,"desconto"=>30,
      "info"=>"","foto"=>"esmeralda-praia-hotel.jpg"],
  ];
?>
