<?php
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
  $hoteis = [
    ["id"=>1,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["algarve hotel turim1.jpg",
          "algarve hotel turim2.jpg",
          "algarve hotel turim3.jpg",
          "algarve hotel turim4.jpg"],
"nome"=>"TURIM Algarve Mor Hotel",
"endereco"=>"Av Tomas Cabreira, Praia Da Rocha, 8500-802 Portimão, Portugal",
"comodidades"=>["wifi"=>true,
                "piscina"=>true,
                "estacionamento"=>true,
                "cafe"=>false,
                "ar-condicionado"=>true,
                "pet"=>false,
                "cancelar"=>false,
                "taxa_reg"=>120,
                "24h"=>true],
"total"=>"",
"quartos"=>[
            ["disponivel"=>true,"casal"=>0,"solteiro"=>2],
                ]
    ],
    ["id"=>2,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["algarve flor da rocha hotel1.jpg",
          "algarve flor da rocha hotel2.jpg",
          "algarve flor da rocha hotel3.jpg",
          "algarve flor da rocha hotel4.jpg"],
"nome"=>"Flor da Rocha",
"endereco"=>"Sitio Dos Castelos, 8500-801 Portimão, Portugal",
"comodidades"=>["wifi"=>true,
                "piscina"=>true,
                "estacionamento"=>true,
                "cafe"=>false,
                "ar-condicionado"=>true,
                "pet"=>false,
                "cancelar"=>120,
                "taxa_reg"=>false,
                "24h"=>true],
"total"=>"",
"quartos"=>[
            ["disponivel"=>true,"casal"=>1,"solteiro"=>0],
                ]
    ],
    ["id"=>3,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["algarve cassino hotel1.jpg",
          "algarve cassino hotel2.jpg",
          "algarve cassino hotel3.jpg",
          "algarve cassino hotel4.jpg"],
"nome"=>"Algarve Cassino Hotel",
"endereco"=>"Av. Tomas Cabreira, 8500-802 Portimão, Portugal",
"comodidades"=>["wifi"=>true,
                "piscina"=>true,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>false,
                "cancelar"=>false,
                "taxa_reg"=>120,
                "24h"=>true],
"total"=>"",
"quartos"=>[
            ["disponivel"=>true,"casal"=>1,"solteiro"=>0],
            ["disponivel"=>true,"casal"=>0,"solteiro"=>2]
                ]
    ],
    ["id"=>4,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["amalfi hotel bellevue1.jpg",
          "amalfi hotel bellevue2.jpg",
          "amalfi hotel bellevue3.jpg",
          "amalfi hotel bellevue4.jpg"],
"nome"=>"Hotel Bellevue Suite ",
"endereco"=>"Via Mauro Comite 26, 84011 Amalfi, Itália",
"comodidades"=>["wifi"=>true,
                "piscina"=>true,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>false,
                "cancelar"=>false,
                "taxa_reg"=>120,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>1,"solteiro"=>0]
                ]
    ],
    ["id"=>5,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["amalfi residenza sole1.jpg",
          "amalfi residenza sole2.jpg",
          "amalfi residenza sole3.jpg",
          "amalfi residenza sole4.jpg"],
"nome"=>"Residenza Sole",
"endereco"=>"Piazza Municipio, 84011 Amalfi, Itália",
"comodidades"=>["wifi"=>true,
                "piscina"=>true,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>true,
                "cancelar"=>false,
                "taxa_reg"=>120,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>2,"solteiro"=>0]
                ]
    ],
    ["id"=>6,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["amalfi nh Collection1.jpg",
          "amalfi nh Collection2.jpg",
          "amalfi nh Collection3.jpg",
          "amalfi nh Collection4.jpg"],
"nome"=>"NH Collection Grand Hotel Convento di Amalfi",
"endereco"=>"Via Annunziatella 46, 84011 Amalfi, Itália",
"comodidades"=>["wifi"=>true,
                "piscina"=>true,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>true,
                "cancelar"=>false,
                "taxa_reg"=>120,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>1,"solteiro"=>0]
                ]
    ],
    ["id"=>7,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["banff banff inn1.jpg",
          "banff banff inn2.jpg",
          "banff banff inn3.jpg",
          "banff banff inn4.jpg"],
"nome"=>"BANFF INN",
"endereco"=>"501 Banff Avenue, T1L 1A9 Banff, Canadá",
"comodidades"=>["wifi"=>true,
                "piscina"=>true,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>false,
                "cancelar"=>false,
                "taxa_reg"=>120,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>2,"solteiro"=>0]
                ]
    ],
    ["id"=>8,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["banff Red Carpet Inn1.jpg",
          "banff Red Carpet Inn2.jpg",
          "banff Red Carpet Inn3.jpg",
          "banff Red Carpet Inn4.jpg"],
"nome"=>"Red Carpet Inn",
"endereco"=>"425 Banff Avenue, T1L 1B6 Banff, Canadá",
"comodidades"=>["wifi"=>true,
                "piscina"=>false,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>true,
                "cancelar"=>false,
                "taxa_reg"=>120,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>2,"solteiro"=>0]
                ]
    ],
    ["id"=>9,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["banff Irwins Mountain Inn1.jpg",
          "banff Irwins Mountain Inn2.jpg",
          "banff Irwins Mountain Inn3.jpg",
          "banff Irwins Mountain Inn4.jpg"],
"nome"=>"Irwin's Mountain Inn",
"endereco"=>"429 Banff Avenue, T1L 1B2 Banff, Canadá",
"comodidades"=>["wifi"=>true,
                "piscina"=>false,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>true,
                "cancelar"=>false,
                "taxa_reg"=>120,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>1,"solteiro"=>0]
                ]
    ],
    ["id"=>10,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["budapeste korona panzio1.jpg",
          "budapeste korona panzio2.jpg",
          "budapeste korona panzio3.jpg",
          "budapeste korona panzio4.jpg"],
"nome"=>"Korona Panzió Budapest",
"endereco"=>"1112 Budapeste, 123 Sasadi út, Hungria",
"comodidades"=>["wifi"=>true,
                "piscina"=>false,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>true,
                "cancelar"=>false,
                "taxa_reg"=>120,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>1,"solteiro"=>0]
                ]
    ],
    ["id"=>11,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["budapeste fashion street1.jpg",
          "budapeste fashion street2.jpg",
          "budapeste fashion street3.jpg",
          "budapeste fashion street4.jpg"],
"nome"=>"Fashion Street Boutique",
"endereco"=>"1052 Budapeste, 17 Váci utca, Hungria",
"comodidades"=>["wifi"=>true,
                "piscina"=>false,
                "estacionamento"=>true,
                "cafe"=>true,
                "ar-condicionado"=>true,
                "pet"=>true,
                "cancelar"=>false,
                "taxa_reg"=>120,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>1,"solteiro"=>0]
                ]
    ],
    ["id"=>12,
"preco"=>200,
"noites"=>2,
"horario"=>["entrada"=>"09:00 2/05","saida"=>"18:00 2/07"],
"hospedes"=>2,
"max"=>2,
"tipo"=>1,
"fotos"=>["budapeste nn apartmanette1.jpg",
          "budapeste nn apartmanette2.jpg",
          "budapeste nn apartmanette3.jpg",
          "budapeste nn apartmanette4.jpg"],
"nome"=>"NN Apartmanette",
"endereco"=>"1051 Budapeste, Nador utca 23, Hungria",
"comodidades"=>["wifi"=>true,
                "piscina"=>false,
                "estacionamento"=>false,
                "cafe"=>false,
                "ar-condicionado"=>true,
                "pet"=>false,
                "cancelar"=>false,
                "taxa_reg"=>false,
"total"=>"",
                "24h"=>true],
"quartos"=>[
            ["disponivel"=>true,"casal"=>1,"solteiro"=>0]
                ]
    ],

  ];

function call_pdt($i){
  global $hoteis;
  foreach($hoteis as $item){if ($item["id"] == $i) {
  return $item;}}
}
?>
